/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    403: typeof import('./src/components/errorPage/403.vue')['default']
    404: typeof import('./src/components/errorPage/404.vue')['default']
    500: typeof import('./src/components/errorPage/500.vue')['default']
    '模板组件': typeof import('./src/components/模板组件.vue')['default']
    AddModal: typeof import('./src/components/page/systemManager/userMaintain/addModal.vue')['default']
    Center: typeof import('./src/components/index/top/TopHeader/Center.vue')['default']
    ClassIcon: typeof import('./src/components/customComponents/icon/ClassIcon.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    DeptMaintain: typeof import('./src/components/page/systemManager/deptMaintain/index.vue')['default']
    EditModal: typeof import('./src/components/page/systemManager/userMaintain/editModal.vue')['default']
    FileUpLoad: typeof import('./src/components/customComponents/fileUpLoad/FileUpLoad.vue')['default']
    FormatText: typeof import('./src/components/customComponents/dict/FormatText.vue')['default']
    Home: typeof import('./src/components/page/home/index.vue')['default']
    Index_old: typeof import('./src/components/index_old.vue')['default']
    Left: typeof import('./src/components/index/top/TopHeader/Left.vue')['default']
    LeftMenus: typeof import('./src/components/index/left/LeftMenus.vue')['default']
    LeftMenusElementPlus: typeof import('./src/components/index/left/LeftMenusElementPlus.vue')['default']
    Loading1: typeof import('./src/components/customComponents/loading/Loading1.vue')['default']
    Loading2: typeof import('./src/components/customComponents/loading/Loading2.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    MenusItem: typeof import('./src/components/index/left/MenusItem.vue')['default']
    MenusRecursion: typeof import('./src/components/index/left/MenusRecursion.vue')['default']
    PasswordModifyModal: typeof import('./src/components/index/top/PasswordModifyModal.vue')['default']
    ProgressCancelFileUpLoad: typeof import('./src/components/customComponents/fileUpLoad/modal/ProgressCancelFileUpLoad.vue')['default']
    ProgressCancelFileUpLoadList: typeof import('./src/components/customComponents/fileUpLoad/modal/ProgressCancelFileUpLoadList.vue')['default']
    Right: typeof import('./src/components/index/top/TopHeader/Right.vue')['default']
    RightContainer: typeof import('./src/components/index/right/RightContainer.vue')['default']
    RightTabs: typeof import('./src/components/index/right/RightTabs.vue')['default']
    RightTabs1: typeof import('./src/components/index/right/RightTabs1.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/customComponents/icon/SvgIcon.vue')['default']
    SystemNotice: typeof import('./src/components/page/home/systemNotice/SystemNotice.vue')['default']
    SystemNoticeDetail: typeof import('./src/components/page/home/systemNotice/SystemNoticeDetail.vue')['default']
    TagList: typeof import('./src/components/index/right/TagList.vue')['default']
    TopHeader: typeof import('./src/components/index/top/TopHeader/index.vue')['default']
    TopHeader1: typeof import('./src/components/index/top/TopHeader1.vue')['default']
    TopHeader2: typeof import('./src/components/index/top/TopHeader2.vue')['default']
    UpLoadTest: typeof import('./src/components/page/test/UpLoadTest.vue')['default']
    UserInfoMaintain: typeof import('./src/components/page/systemManager/userInfoMaintain/index.vue')['default']
    UserMaintain: typeof import('./src/components/page/systemManager/userMaintain/index.vue')['default']
  }
}
